### ISSUE TITLE
No python bindings on linux python 3 system

### ISSUE THREAD

**Issue by tammojan** [conda-forge/casacore-feedstock#6]
On an ubuntu 14.04 system with Anaconda3 (the anaconda with python 3.6) `libcasa_python` seems to be not built:
```
bash Anaconda3-4.4.0-Linux-x86_64.sh
conda config --add channels conda-forge
. ~/.bashrc # Load the anaconda path
python --version
  --> Python 3.6.1 :: Anaconda custom (64-bit)
python -c "import casacore.tables"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/lib/python3.6/site-packages/casacore/tables/__init__.py", line 60, in <module>
    from .table import table
  File "/root/anaconda3/lib/python3.6/site-packages/casacore/tables/table.py", line 44, in <module>
    from ._tables import Table
ImportError: libcasa_python3.so.2: cannot open shared object file: No such file or directory
```
Indeed no `casa_python` is found:
```
ls -l /root/anaconda3/lib/libcasa_*
/root/anaconda3/lib/libcasa_casa.so          /root/anaconda3/lib/libcasa_measures.so
/root/anaconda3/lib/libcasa_coordinates.so   /root/anaconda3/lib/libcasa_mirlib.so
/root/anaconda3/lib/libcasa_derivedmscal.so  /root/anaconda3/lib/libcasa_ms.so
/root/anaconda3/lib/libcasa_fits.so          /root/anaconda3/lib/libcasa_msfits.so
/root/anaconda3/lib/libcasa_images.so        /root/anaconda3/lib/libcasa_scimath.so
/root/anaconda3/lib/libcasa_lattices.so      /root/anaconda3/lib/libcasa_scimath_f.so
/root/anaconda3/lib/libcasa_meas.so          /root/anaconda3/lib/libcasa_tables.so 
```
I'm new to conda packaging, can't fix this myself yet. It would be great if we could use the conda recipes for testing python-casacore on travis, see casacore/python-casacore#91

**Comment by tammojan** [comment]
It works fine on Ubuntu 14.04 with a python 2.7 conda:
```
bash Miniconda2-latest-Linux-x86_64.sh
export PATH="$HOME/miniconda/bin:$PATH"
conda config --add channels conda-forge
conda install python-casacore
which python
--> 
python --version
--> Python 2.7.13 :: Continuum Analytics, Inc.
python -c "import casacore.tables" # No error
ls ~/miniconda/lib/libcasa_python.so*
/root/miniconda/lib/libcasa_python.so  /root/miniconda/lib/libcasa_python.so.2  /root/miniconda/lib/libcasa_python.so.2.2.0
```

**Comment by pkgw** [comment]
Are you sure that the right version of the `casacore` package is installed? It should have the build tag `py36_3` or `py35_3`. I can confirm that this version does provide the needed library.

`conda-forge` is currently updating `hdf5` to deal with a security vulnerability, so if your Anaconda has packages installed that still require the old `hdf5`, you won't be able to upgrade due to the version mismatch. The command 

```
conda install 'casacore =2.2.0 py36_3'
```

may give you insight into why you can't upgrade, if that's the case.
